Replace print statment with print function
In PY3, print should used as a function instead of a statement.
This is PY27 compatible as well.

For example, instances of the first case were replaced by the
second case:

>>> print 'help'
  File "<stdin>", line 1
    print 'help'
               ^
SyntaxError: Missing parentheses in call to 'print'

>>> print('help')
help

Partially implements: blueprint trove-python3
Change-Id: I21de65bc874d0fcfb51714857f8eaa97acb2f51d
Closes-bug: #1594741