Fix cloudinit mariadb scenario test error
For now mariadb scenario single test case fails because the script
cannot find cloudinit file.

This change adds cloudinit file creation if the file doesn't exist.

Before this patch we were getting the following message:
    tee: /etc/trove/cloudinit/mysql.cloudinit: No such file or
    directory
    #!/bin/sh
    ERROR: InvocationError for command /opt/stack/trove/integration/
    scripts/trovestack gate-tests mariadb mariadb-supported-single
    (exited with code 1)

Change-Id: Iea74dc2c58b1c4376c698f0084454cfcbb3f3b7d
Signed-off-by: Kasper Hasior <k.hasior@samsung.com>