Fix tox py27 error
The backup.test_backupagent.BackupAgentTest.test_backup_impl_MongoDump
unit test throws the following error when we run tox -r -e py27:
AttributeError: 'NoneType' object has no attribute 'rfind'

The error is caused by a 'None' CONFIG_FILE value being passed into the
os.path.dirname(CONFIG_FILE) call.

The CONFIG_FILE value is derived from the return value of the
trove.guestagent.common.operating_system.file_discovery() method, which
shouldn't be None.

This commit ensures the file_discovery() method would never return a
'None' value.

Change-Id: Id2f1f72e1a9e303c7b59ff0d25c556bc89de4669
Closes-Bug: 1515642