Update gate jobs as per the 2025.1 cycle testing runtime
As per 2025.1 testing runtime[1], we need to test on Ubuntu
Noble (which will be taken care by tempest and devstack [2]
patches to move base jobs to Noble) and at least single job to run on
Ubuntu Jammy (for smooth upgrade from previous releases).

This commit adds a new job to run on Jammy which can be removed
in future cycle when testing runtime test next version of Ubuntu
as default.

Also bump the hacking version to fix the pepe8 erorr:
 -AttributeError: 'EntryPoints' object has no attribute 'get'

[1] https://governance.openstack.org/tc/reference/runtimes/2025.1.html
[2] https://review.opendev.org/c/openstack/tempest/+/932156

Change-Id: Ia29391d5535b16589d7cf259f958b3b6aac5776c