Fix replication detach error
TypeError: tuple indices must be integers or slices, not str

this is caused by the new version of the sqlachemy library.

Change-Id: I76166f901f961a18ad4297d04e1a75a59b059e23
(cherry picked from commit f0f186ef9a278c919cfba331a05f2f1b3fa6a572)