Fix error in mysql xtrabackup incremental backups
Currently, trove-tempest-ubuntu-backup-mysql8.4 job fails with error:
ValueError: Version string lacks a numerical component: '[Note]'
The problem is caused by incostistent output of xtrabackup --version
command. Proposed solution is to write file with version during
install script run.

Change-Id: I3be573f87c8e7619fb2002f2f773a9c6fd765be5
Signed-off-by: Erkin Mussurmankulov <mangust404@gmail.com>
(cherry picked from commit cd853fb2f16b4c30c70d3c1cb057d4dfe76c1219)